export type SpriteTypes =
  | "icon-arrow-r"
  | "icon-attachment"
  | "icon-check"
  | "icon-chevron-r"
  | "icon-error"
  | "icon-eye-off"
  | "icon-eye"
  | "icon-hourglass"
  | "icon-icon"
  | "icon-pie-chart"
  | "icon-trash"
  | "icon-x"
  | "icon-burger1"
  | "icon-hourglass-01"
  | "icon-pie-chart-02"
  | "icon-hourglass-02"
  | "icon-pie-chart-03";
