import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/components/AuthProvider";
import { ModalProvider } from "@/components/ModalProvider";
import ModalManager from "@/modals/ModalsManager";

export const metadata: Metadata = {
  title: "Book App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="p-5 md:p-8">
        <AuthProvider>
          <ModalProvider>
            {children}
            <ModalManager />
          </ModalProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
