import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/components/Providers/AuthProvider";
import { ModalProvider } from "@/components/Providers/ModalProvider";
import ModalManager from "@/components/Modals/ModalsManager";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Book App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ModalProvider>
            <ToastContainer
              position="top-right"
              autoClose={4000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick={true}
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="dark"
            />
            {children}
            <ModalManager />
          </ModalProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
